#!/bin/sh

. /usr/share/libubox/jshn.sh


do_update() {
    local dir="/usr/share/xray"
    local tmpdir="/tmp"
    local file_name="$1"
    local down_url="$2"

    echo "update $file_name begin..." > $dir/xray_update_msg.log

    rm -f "$tmpdir/$file_name.sha256sum"
    rm -f "$tmpdir/$file_name"
    mkdir -p $dir

    echo "downloading $file_name, url: $down_url " >> $dir/xray_update_msg.log

    wget -q -O "$tmpdir/$file_name.sha256sum" "$down_url.sha256sum" > /dev/null 2>&1
    wget -q -O "$tmpdir/$file_name" "$down_url" > /dev/null 2>&1
    echo "$file_name downloaded." >> $dir/xray_update_msg.log

    cd $tmpdir && sha256sum -c "$file_name.sha256sum" >> $dir/xray_update_msg.log 2>&1
    if [ $? -eq 0 ] ; then

        if [ -s $tmpdir/$file_name ] ; then

            echo "stop xray_core..." >> $dir/xray_update_msg.log
            /etc/init.d/xray_core stop

            [ -s "$dir/$file_name" ] && [ -s "$dir/$file_name.sha256sum" ] && {
                cd $dir && sha256sum -c $file_name.sha256sum >> $dir/xray_update_msg.log 2>&1
                [ $? -eq 0 ] && {
                    echo "move $dir/$file_name to $dir/$file_name.save " >> $dir/xray_update_msg.log
                    mv -f "$dir/$file_name" "$dir/$file_name.save" > /dev/null 2>&1
                }
            }

            echo "move $tmpdir/$file_name to $dir/$file_name ">> $dir/xray_update_msg.log
            mv -f "$tmpdir/$file_name" "$dir/$file_name"
            mv -f "$tmpdir/$file_name.sha256sum" "$dir/$file_name.sha256sum"
            chmod 444 "$dir/$file_name" "$dir/$file_name.sha256sum"

            echo "start xray_core..." >> $dir/xray_update_msg.log
            /etc/init.d/xray_core start

            echo "update $file_name finished." >> $dir/xray_update_msg.log
            echo '{ "code": 0 }'
        else
            echo "download file is empty, update failed." >> $dir/xray_update_msg.log

            echo '{ "code": 1, "msg": "empty file" }'
        fi
    else
        echo "download file sha256sum error, update failed." >> $dir/xray_update_msg.log

        echo "{ \"code\": 1, \"msg\": \"$(cat /tmp/xray_update_msg.log)\" }"
    fi
}

update_geosite() {
    do_update "geosite.dat" "$1"
}

update_geoip() {
    do_update "geoip.dat" "$1"
}

main() {
    case "$1" in
        list)
            echo '{"statsquery":{},"statssys":{},"restartlogger":{},"updatedatafile":{"name": "String", "url": "String"}}'
            ;;
        call)
            case "$2" in
                statsquery)
                    shift
                    xray api $@
                ;;
                statssys)
                    shift
                    xray api $@
                ;;
                restartlogger)
                    shift
                    xray api $@
                ;;
                updatedatafile)
                    read input;

                    json_set_namespace "xray_updatedatafile" old_ns

                    json_load "$input"
                    json_get_var file_name "name"
                    json_get_var url "url"

                    json_cleanup

                    json_set_namespace "$old_ns"

                    update_"$file_name" "$url"
                ;;
            esac
    esac
}

main "$@"
